
export const LOAD_COMMUNAL_APARTMENTS = "LOAD_COMMUNAL_APARTMENTS"; 

export const DELETE_SELECTED_COMMUNAL_APPARTMENTS = "DELETE_COMMUNAL_APPARTMENTS";

export const DENY_DELETION = "DENY_DELETION";

export const CONFIRM_DELETION = "CONFIRM_DELETION";

export const UNSELECT_COMUNAL_APARTMENT = "UNSELECT_COMUNAL_APARTMENT";

export const USNSELECT_ALL_COMMUNAL_APARTMENTS ="USNSELECT_ALL_COMMUNAL_APARTMENTS";

export const SELECT_COMMUNAL_APPARTMENT = "SELECT_COMMUNAL_APPARTMENT";

export const LOAD_NEXT_COMMUNAL_APPARTMENTS_PART = "LOAD_NEXT_COMMUNAL_APPARTMENTS_PART";

export const SET_FILTER_PRICE_FROM ="FILTER_PRICE_FROM";
export const SET_FILTER_PRICE_TO = "SET_FILTER_PRICE_TO";

export const SET_COMMUNAL_APARTMENTS_ORDERING ="SET_COMMUNAL_APARTMENTS_ORDERING";