export const ADD_COMUNAL_APARTMENT : string
 = "ADD_COMUNAL_APARTMENT";

export const ADD_RANGE_COMUNAL_APARTMENTS ="ADD_RANGE_COMUNAL_APARTMENTS";

export const HIDE_MODAL = "HIDE_MODAL";

export const SHOW_MODAL = "SHOW_MODAL";

export const REMOVE_COMUNAL_APARTMENTS="REMOVE_COMUNAL_APARTMENT";

export const SELECT_COMUNAL_APARTMENT = "SELECT_COMUNAL_APARTMENT";

export const UNSELECT_COMUNAL_APARTMENT = "UNSELECT_COMUNAL_APARTMENT";

export const CLEARE_SELECTED_COMUNAL_APARTMENTS ="CLEARE_SELECTED_COMUNAL_APARTMENTS";

export const LOAD_NEXT_COMMUNAL_APPARTMENTS_PART = "LOAD_NEXT_PAGE";

export const SET_FILTER_PRICE_FROM ="FILTER_PRICE_FROM";
export const SET_FILTER_PRICE_TO = "SET_FILTER_PRICE_TO";

export const SET_COMMUNAL_APARTMENTS_ORDERING = "SET_COMMUNAL_APARTMENTS_ORDERING";